version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: build
    binary: build
    main: cmd/build/main.go
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    goos:
      - linux
      - darwin
  - id: detect
    binary: detect
    main: cmd/detect/main.go
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    goos:
      - linux
      - darwin

archives:
  - formats: [binary]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
