api = "0.7"

[buildpack]
  id = "runway-buildpacks/static-websites"
  name = "Static Buildpack"
  version = "__replace__"
  homepage = "https://www.runway.horse/docs/"
  keywords = ["hugo", "mdbook", "static website generator"]
  description = "A buildpack for Hugo & mdbook (by Runway)"

  [[buildpack.licenses]]
    type = "BSD-2-Clause"
    uri = "https://github.com/hostwithquantum/static-buildpack/blob/main/LICENSE"

[metadata]
  include-files = ["bin/build", "bin/detect", "buildpack.toml"]
  pre-package = "make package"