api = "0.7"

[buildpack]
  id = "runway-buildpacks/static-websites"
  name = "Static Buildpack"
  version = "__replace__"
  homepage = "https://www.runway.horse/docs/"
  keywords = ["hugo", "mdbook", "static website generator"]
  description = "A buildpack for Hugo & mdbook (by Runway)"

  [[buildpack.licenses]]
    type = "MPL-2.0"
    uri = "https://github.com/hostwithquantum/static-buildpack/blob/main/LICENSE"

[metadata]
  include-files = ["linux/amd64/bin/build", "linux/amd64/bin/detect", "linux/arm64/bin/build", "linux/arm64/bin/detect", "buildpack.toml"]
  pre-package = "make build"

  [[metadata.configurations]]
    default = ""
    description = "A relative path to the hugo or mdbook site, will be appended to the working directory"
    name = "BP_RUNWAY_STATIC_PATH"

  [[metadata.configurations]]
    default = "0.160.1"
    description = "Hugo version to install"
    name = "BP_RUNWAY_STATIC_HUGO_VERSION"

  [[metadata.configurations]]
    default = "0.5.2"
    description = "MdBook version to install"
    name = "BP_RUNWAY_STATIC_MDBOOK_VERSION"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
