api = "0.7"

[buildpack]
id = "meta-buildpack"
version = "0.1.1"
name = "Hugo + webserver stack -- here only used for testing"

[[order]]
  [[order.group]]
    id = "paketo-buildpacks/go-dist"
    version = "*"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/git"
    optional = true
    version = "*"

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    optional = true
    version = "*"

  [[order.group]]
    id = "paketo-buildpacks/npm-install"
    optional = true
    version = "*"

  [[order.group]]
    id = "paketo-buildpacks/node-run-script"
    optional = true
    version = "*"

  [[order.group]]
    id = "paketo-buildpacks/nginx"
    version = "*"
    optional = true

  [[order.group]]
    id = "static-buildpack"
    version = "dev"

[[order]]
  [[order.group]]
    id = "paketo-buildpacks/go-dist"
    version = "*"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/git"
    optional = true
    version = "*"

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    optional = true
    version = "*"

  [[order.group]]
    id = "paketo-buildpacks/npm-install"
    optional = true
    version = "*"

  [[order.group]]
    id = "paketo-buildpacks/node-run-script"
    optional = true
    version = "*"

  [[order.group]]
    id = "paketo-buildpacks/httpd"
    version = "*"
    optional = true

  [[order.group]]
    id = "static-buildpack"
    version = "dev"
