api = "0.7"

[buildpack]
id = "meta-buildpack"
version = "0.1.1"
name = "Hugo + webserver stack -- here only used for testing"

[[order]]
  [[order.group]]
    id = "paketo-buildpacks/go-dist"
    optional = true
    version = "2.7.15"

  [[order.group]]
    id = "paketo-buildpacks/git"
    optional = true
    version = "1.0.62"

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    optional = true
    version = "7.3.0"

  [[order.group]]
    id = "paketo-buildpacks/npm-install"
    optional = true
    version = "2.1.0"

  [[order.group]]
    id = "paketo-buildpacks/node-run-script"
    optional = true
    version = "2.1.15"

  [[order.group]]
    id = "paketo-buildpacks/nginx"
    optional = true
    version = "0.18.0"

  [[order.group]]
    id = "runway-buildpacks/static-websites"
    version = "dev"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/go-dist"
    optional = true
    version = "2.7.15"

  [[order.group]]
    id = "paketo-buildpacks/git"
    optional = true
    version = "1.0.62"

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    optional = true
    version = "7.3.0"

  [[order.group]]
    id = "paketo-buildpacks/npm-install"
    optional = true
    version = "2.1.0"

  [[order.group]]
    id = "paketo-buildpacks/node-run-script"
    optional = true
    version = "2.1.15"

  [[order.group]]
    id = "paketo-buildpacks/httpd"
    optional = true
    version = "0.7.63"

  [[order.group]]
    id = "runway-buildpacks/static-websites"
    version = "dev"