api = "0.7"

[buildpack]
id = "meta-buildpack"
version = "0.1.0"
name = "Hugo + NGINX Stack"

[[order]]
  [[order.group]]
    id = "static-buildpack"

  [[order.group]]
    id = "paketo-buildpacks/nginx"
    version = "0.17.24"