name: pr

on:
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  build:
    env:
      DOCKER_REGISTRY: "ttl.sh"
      BUILD_DIR: build
    outputs:
      package: ${{ steps.setup.outputs.package }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - uses: buildpacks/github-actions/setup-tools@v5.9.3
      - uses: buildpacks/github-actions/setup-pack@v5.9.3
      - id: setup
        shell: bash
        run: |
          DOCKER_REPO=$(uuidgen)
          PACKAGE="${{ env.DOCKER_REGISTRY }}/${DOCKER_REPO}:20m"
          echo "package=${PACKAGE}" >> $GITHUB_OUTPUT
          echo "Generated name: ${PACKAGE}" >> $GITHUB_STEP_SUMMARY
      - uses: goreleaser/goreleaser-action@v6
        with:
          version: '~> v2'
          args: release --snapshot --clean
      - run: make setup
      - run: make prep VERSION=dev BUILD_DIR=${{ env.BUILD_DIR }}
      - run: |
          pack buildpack package \
            ${{ steps.setup.outputs.package }} \
            --target linux/amd64 \
            --config package.toml
        working-directory: ${{ env.BUILD_DIR }}
      - name: publish temporary image
        run: |
          docker push ${{ steps.setup.outputs.package }}

  test:
    needs: build
    runs-on: ubuntu-latest
    name: ${{ matrix.test }}-${{ matrix.webserver }}
    strategy:
      matrix:
        test: [test-hugo, test-hugo-npm, test-mdbook, test-hugo-go]
        webserver: [nginx, httpd]
    steps:
      - uses: actions/checkout@v5
      - run: docker pull ${{ needs.build.outputs.package }}
      - name: Update meta-buildpack package.toml
        run: |
          sed -i 's|docker://r.planetary-quantum.com/buildpacks/static-websites:latest|docker://${{ needs.build.outputs.package }}|' meta-buildpack/package.toml
      - uses: buildpacks/github-actions/setup-tools@v5.9.3
      - uses: buildpacks/github-actions/setup-pack@v5.9.3
      - run: make setup
      - run: make ${{ matrix.test }}-${{ matrix.webserver }}
      - name: verify the correct webserver is installed
        run: |
          docker run --rm \
            --entrypoint launcher \
            ${{ matrix.test }}-${{ matrix.webserver }}-app \
            ${{ matrix.webserver }} -v
