name: pr

on:
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  build:
    env:
      DOCKER_REGISTRY: "r.planetary-quantum.com"
      DOCKER_REPO: "buildpacks"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - uses: buildpacks/github-actions/setup-tools@v5.9.3
      - uses: buildpacks/github-actions/setup-pack@v5.9.3
      - id: extract-package
        shell: bash
        run: |
          BP_ID="$(cat buildpack.toml | yj -t | jq -r '.buildpack.id | split("/")[1]')"
          PACKAGE="${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPO }}/${BP_ID}"
          echo "package=${PACKAGE}" >> $GITHUB_OUTPUT
          echo "Generated name: ${PACKAGE}" >> $GITHUB_STEP_SUMMARY
      - run: sed -i.bak -E "s/__replace__/dev/" buildpack.toml
      - uses: goreleaser/goreleaser-action@v6
        with:
          version: '~> v2'
          install-only: true
      - run: make package
      - name: Export buildpack image
        run: |
          docker save runway-buildpacks/static-websites:latest -o static-buildpack.tar
      - uses: actions/upload-artifact@v4
        with:
          name: static-buildpack
          path: static-buildpack.tar
          retention-days: 1

  test:
    needs: build
    runs-on: ubuntu-latest
    name: ${{ matrix.test }}-${{ matrix.webserver }}
    strategy:
      matrix:
        test: [test-hugo, test-hugo-npm, test-mdbook, test-hugo-go]
        webserver: [nginx, httpd]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/download-artifact@v5
        with:
          name: static-buildpack
      - run: docker load -i static-buildpack.tar
      - run: docker images runway-buildpacks/static-websites:latest
      - uses: buildpacks/github-actions/setup-tools@v5.9.3
      - uses: buildpacks/github-actions/setup-pack@v5.9.3
      - run: make setup
      - run: make ${{ matrix.test }}-${{ matrix.webserver }}
      - name: verify the correct webserver is installed
        run: |
          docker run --rm \
            --entrypoint launcher \
            ${{ matrix.test }}-${{ matrix.webserver }}-app \
            ${{ matrix.webserver }} -v
